filter:
    paths:
    - 'src/*'
    excluded_paths:
    - 'src/**/Tests'
    - 'src/**/Resources'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false

build:
    dependencies:
        override:
            - composer install --no-interaction  --prefer-source
    tests:
        ovveride:
        -
            command: bin/phpuint -c app --coverage-clover=coverage.xml
            coverage:
                file: coverage.xml
                format: php-clover
