<?php

namespace Illuminati\OrderBundle\Entity;

/**
 * Host_order_stateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Host_order_stateRepository extends \Doctrine\ORM\EntityRepository
{
}
