<?php

namespace Illuminati\OrderBundle\Entity;

/**
 * Host_orderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Host_orderRepository extends \Doctrine\ORM\EntityRepository
{
}
