<?php

namespace Illuminati\OrderBundle\Entity;

/**
 * Order_participantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order_participantsRepository extends \Doctrine\ORM\EntityRepository
{
}
