<?php

namespace Illuminati\OrderBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User_order_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_order_detailsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $userId
     * @param $orderId
     * @return mixed
     */
    public function deleteAllUserOrderedDetails($userId, $orderId)
    {
        $dql = '
        DELETE
            IlluminatiOrderBundle:User_order_details od
        WHERE
        (od.userId = :userId) AND
        (od.hostOrderId = :hostOrderId)';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('userId', $userId)
            ->setParameter('hostOrderId', $orderId)
            ->execute();
    }

    /**
     * @param $userId
     * @param $orderId
     * @return mixed
     */
    public function getAllUserOrderedDetails($userId, $orderId)
    {
        $dql = '
        SELECT od
        FROM
            IlluminatiOrderBundle:User_order_details od
        WHERE
        (od.userId = :userId) AND
        (od.hostOrderId = :hostOrderId)';

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('userId', $userId)
            ->setParameter('hostOrderId', $orderId)
            ->execute();
    }

    /**
     * @param $order
     * @param $product
     * @param $quantity
     * @param $user
     * @return User_order_details
     */
    public function createUserOrderDetailsItem($order, $product, $quantity, $user)
    {
        $userOrderDetails = new User_order_details();

        $userOrderDetails->setHostOrderId($order);
        $userOrderDetails->setProductId($product);
        $userOrderDetails->setQuantity($quantity);
        $userOrderDetails->setUserId($user);

        $this->getEntityManager()->persist($userOrderDetails);
        $this->getEntityManager()->flush();

        return $userOrderDetails;
    }
}
