<?php

namespace Illuminati\OrderBundle\Entity;

/**
 * User_orderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_orderRepository extends \Doctrine\ORM\EntityRepository
{
}
