<?php

namespace Illuminati\OrderBundle\Entity;

/**
 * User_order_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_order_detailsRepository extends \Doctrine\ORM\EntityRepository
{
}
