product:
    path:     /{orderId}
    defaults: { _controller: "ProductBundle:Product:index" }

product_show:
    path:     /{id}/order/{orderId}
    defaults: { _controller: "ProductBundle:Product:show" }