supplier:
    path:     /
    defaults: { _controller: "ProductBundle:Supplier:index" }

supplier_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:Supplier:show" }

supplier_new:
    path:     /new
    defaults: { _controller: "ProductBundle:Supplier:new" }

supplier_create:
    path:     /create
    defaults: { _controller: "ProductBundle:Supplier:create" }
    methods:  POST

supplier_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:Supplier:edit" }

supplier_update:
    path:     /{id}/update
    defaults: { _controller: "ProductBundle:Supplier:update" }
    methods:  [POST, PUT]

supplier_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:Supplier:delete" }
    methods:  [POST, DELETE]
