illuminati_order:
    resource: "@IlluminatiOrderBundle/Controller/"
    type:     annotation
    prefix:   /order

illuminati_user:
    resource: "@IlluminatiUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
