cart_add:
    path:     /cart/add/product/{product_id}/order/{order_id}
    defaults: { _controller: CartBundle:Cart:add }
cart_remove:
    path:     /cart/remove/product/{product_id}/order/{order_id}
    defaults: { _controller: CartBundle:Cart:remove }
cart_checkout:
    path:     /checkout/{order_id}
    defaults: { _controller: CartBundle:Cart:checkout }
